import axios from "axios";
import React, { useState, useEffect } from "react";
import {
  FAQOut,
  FAQPart,
  FAQLeft,
  FAQTitle,
  FAQList,
  FAQItem,
  PlusImg,
  FAQRight,
  FAQBody,
  FAQMain,
} from "./faq.style";
const MainPage = () => {
  const [faqflag, setfaqflag] = useState(false);
  const [openflag, setopenflag] = useState(0);
  const [data, setData] = useState<any>({
    faqTitle: [],
    faqContent: [],
  });
  useEffect(() => {
    const getData = async () => {
      const query = await axios({
        url: "https://api-ca-central-1.graphcms.com/v2/cl14bkut8eyl601za5bmkb9kr/master",
        method: "post",
        data: {
          query: `
            query {
              faqs {
                faqTitle
                faqContent
              }
            }
          `,
        },
      });
      setData(query.data.data.faqs[0]);
    };
    getData();
  }, []);
  const OpenFAQ = (e: any) => {
    if (openflag == e) {
      setfaqflag(!faqflag);
    } else {
      setopenflag(e);
      setfaqflag(true);
    }
  };
  return (
    <>
      <FAQOut id="faq">
        <FAQPart>
          <FAQLeft>
            <FAQTitle>FAQ</FAQTitle>
              <FAQList>
                <FAQItem onClick={() => OpenFAQ(2)} key={2}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 2 && faqflag && true}
                      alt=""
                    />
                    What is blockchain?
                  </FAQMain>
                  {faqflag && openflag == 2 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `Blockchain is a distributed and decentralized system used to store blocks of transactions and verify them with a network of nodes. These blocks cannot be altered once verified.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(1)} key={1}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 1 && faqflag && true}
                      alt=""
                    />
                    What is a metaverse?
                  </FAQMain>
                  {faqflag && openflag == 1 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `The Metaverse is a virtual world, one to which we will connect using a series of devices that will make us think that we are really inside it, interacting with all its elements.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(3)} key={3}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 3 && faqflag && true}
                      alt=""
                    />
                    What are NFTs?
                  </FAQMain>
                  {faqflag && openflag == 3 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `NFT stands for Non-Fungible Token, a non-fungible token. Tokens are units of value that are assigned to a business model, such as cryptocurrencies.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(4)} key={4}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 4 && faqflag && true}
                      alt=""
                    />
                    What is mixed reality (XR)?
                  </FAQMain>
                  {faqflag && openflag == 4 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `Mixed reality is a blend of physical and digital universes, enabling natural and intuitive 3D interactions between people, teams, and the environment.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(5)} key={5}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 5 && faqflag && true}
                      alt=""
                    />
                    What is virtual reality (VR)?
                  </FAQMain>
                  {faqflag && openflag == 5 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `It is an environment of scenes and objects with a real appearance —generated by computer technology— that creates in the user the sensation of being immersed in it. Said environment is contemplated through a device known as Virtual Reality glasses or helmet.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(6)} key={6}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 6 && faqflag && true}
                      alt=""
                    />
                    What is exchange?
                  </FAQMain>
                  {faqflag && openflag == 6 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `We can define the exchange as a virtual platform or market in which we can carry out cryptocurrency exchanges, either buy or sell. These serve as an intermediary and facilitate the financial movements of users.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(7)} key={7}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 7 && faqflag && true}
                      alt=""
                    />
                    What is cryptocurrency?
                  </FAQMain>
                  {faqflag && openflag == 7 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `A cryptocurrency is a digital asset that uses cryptographic encryption to guarantee its ownership and ensure the integrity of transactions, and control the creation of additional units, that is, preventing someone from making copies as we would, for example, with a photo.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(8)} key={8}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 8 && faqflag && true}
                      alt=""
                    />
                    What is DAPP?
                  </FAQMain>
                  {faqflag && openflag == 8 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `They are decentralized applications that use 'blockchain' so that users relate directly to each other and close agreements, without there being a central entity that manages the service.`,
                      }}
                    />
                  )}
                </FAQItem>
                <FAQItem onClick={() => OpenFAQ(9)} key={9}>
                  <FAQMain>
                    <PlusImg
                      src="img/plus.svg"
                      flag={openflag == 9 && faqflag && true}
                      alt=""
                    />
                    How can we help?
                  </FAQMain>
                  {faqflag && openflag == 9 && (
                    <FAQBody
                      dangerouslySetInnerHTML={{
                        __html: `From the development of a blockchain network, metaverses, NFTs, video games, real estate Tokenization, dapps and web3 apps. We develop the necessary tools so that your idea becomes a reality and you can start the path to success.`,
                      }}
                    />
                  )}
                </FAQItem>
            </FAQList>
          </FAQLeft>
          <FAQRight src="img/carrot.png" alt="" />
        </FAQPart>
      </FAQOut>
    </>
  );
};
export default MainPage;
